server:
  port: 8080
spring:
  application:
    name: burny_cloud
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.62:3306/burny?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: burny
    password: Burny@2024
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: tech.burny
    - group: '权限'
#      paths-to-match: '/**'
      packages-to-scan: tech.burny.security
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


logging:
  level:
    root: debug

